[phases.setup]
  nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensionsmysqli", "nodejs", "npm"]

[phases.install]
  cmds = ["composer install --optimize-autoloader --no-dev"]

[phases.build]
  cmds = ["npm run build"]

[phases.start]
  cmds = ["php artisan migrate --force", "php artisan serve --host=0.0.0.0 --port=$PORT"]

[start]
  cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
